name: Sentinel CI

on:
  push:
    branches:
      - main
      - sprint-*
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Sync Dependencies
        run: uv sync --all-groups

      - name: Ruff
        run: uv run ruff check .

      - name: Black
        run: uv run black --check .

      - name: MyPy
        run: uv run mypy src tests

      - name: Pytest
        run: uv run pytest -v
